# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core "postgres"
#    - container: pg12
#      image: postgres-windows:12
#      ports:
#      - 5432
#      volumes:
#          - '/data/db:/var/lib/postgresql/data'
      

trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

resources:
  containers:
    - container: db
      image: 'postgres'
      ports:
      - 5432
      
jobs:
- job: "Run_Test_Suite"
  pool:
    vmImage: winamd64/docker

  services:
    db: db

  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'


  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: Docker@2
    inputs:
      command: 'start'
      container: 'db'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/tests/*.csproj'

